name: flutter_midi
description: A FLutter Plugin to Play midi on iOS and Android.
version: 1.0.2
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/flutter_midi

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  tonic: ^0.2.3
  plugin_platform_interface: ^2.0.0
  flutter_midi_platform_interface: # any
    path: ../flutter_midi_platform_interface

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterMidiPlugin
      android:
        package: com.appleeducate.fluttermidi
        pluginClass: FlutterMidiPlugin
      # web:
      #   default_package: flutter_midi_web
      # macos:
      #   pluginClass: FlutterMidiPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^4.1.1

environment:
  sdk: ">=2.12.0 <3.0.0"
